version: v1
services:
- name: tcir-register-api
  alias: register-api
  image: automation-technology
  replicas: 1
  env: register-api
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: tcir-mail-consumer
  alias: mail-consumer
  image: automation-technology
  replicas: 1
  env: mail-consumer
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: tcir-batch-scheduler
  alias: batch-scheduler
  image: automation-technology
  replicas: 1
  env: batch-scheduler
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: tcir-batch-ptask-api
  alias: batch-ptask-api
  image: automation-technology
  replicas: 1
  env: batch-ptask-api
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: tcir-batch-ptask-worker
  alias: batch-ptask-worker
  image: automation-technology
  replicas: 1
  env: batch-ptask-worker
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: tcir-external-api
  alias: external-api
  image: automation-technology
  replicas: 1
  env: external-api
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: db-els1
  alias: els1
  image: els
  elsId: els1
  minimumMasterNode: 2
  clusters: els1,els2,els3
  heapSize: 500m
  maxClauseCount: 500000
  queryCacheSize: 30%
  bulkQueueSize: 500
  indexQueueSize: 1000
  snapshotS3Key:
  snapshotS3Secret:
  minMem: 600Mi
  maxMem: 14Gi
  minCpu: 100m
  maxCpu: 2000m
- name: db-els2
  alias: els2
  image: els
  elsId: els2
  minimumMasterNode: 2
  clusters: els1,els2,els3
  heapSize: 500m
  maxClauseCount: 500000
  queryCacheSize: 30%
  bulkQueueSize: 500
  indexQueueSize: 1000
  snapshotS3Key:
  snapshotS3Secret:
  minMem: 600Mi
  maxMem: 14Gi
  minCpu: 100m
  maxCpu: 2000m
- name: db-els3
  alias: els3
  image: els
  elsId: els3
  minimumMasterNode: 2
  clusters: els1,els2,els3
  heapSize: 500m
  maxClauseCount: 500000
  queryCacheSize: 30%
  bulkQueueSize: 500
  indexQueueSize: 1000
  snapshotS3Key:
  snapshotS3Secret:
  minMem: 600Mi
  maxMem: 14Gi
  minCpu: 100m
  maxCpu: 2000m
- name: db-kfk1
  alias: kfk1
  image: kfk
  kfkId: kfk1
  kafkaBrokerID: 1
  kafkaPortNumber: 9092
  kafkaNumPartitions: 5
  kafkaZookeeperConnect: zk1:2181,zk2:2181,zk3:2181
  kafkaNumNetworkThreads: 3
  kafkaNumIOThreads: 4
  kafkaSocketSendBuffeBytes: 102400
  kafkaSocketReceiveBufferBytes: 102400
  kafkaSocketRequestMaxBytes: 104857600
  kafkaMaxMessageBytes: 1000012
  kafkaHeapOpts: -Xmx500m -Xms500m
  minMem: 600Mi
  minCpu: 100m
  maxMem: 6Gi
  maxCpu: 1500m
- name: db-kfk2
  alias: kfk2
  image: kfk
  kfkId: kfk2
  kafkaBrokerID: 2
  kafkaPortNumber: 9092
  kafkaNumPartitions: 5
  kafkaZookeeperConnect: zk1:2181,zk2:2181,zk3:2181
  kafkaNumNetworkThreads: 3
  kafkaNumIOThreads: 4
  kafkaSocketSendBuffeBytes: 102400
  kafkaSocketReceiveBufferBytes: 102400
  kafkaSocketRequestMaxBytes: 104857600
  kafkaMaxMessageBytes: 1000012
  kafkaHeapOpts: -Xmx500m -Xms500m
  minMem: 600Mi
  minCpu: 100m
  maxMem: 6Gi
  maxCpu: 1500m
- name: db-kfk3
  alias: kfk3
  image: kfk
  kfkId: kfk3
  kafkaBrokerID: 3
  kafkaPortNumber: 9092
  kafkaNumPartitions: 5
  kafkaZookeeperConnect: zk1:2181,zk2:2181,zk3:2181
  kafkaNumNetworkThreads: 3
  kafkaNumIOThreads: 4
  kafkaSocketSendBuffeBytes: 102400
  kafkaSocketReceiveBufferBytes: 102400
  kafkaSocketRequestMaxBytes: 104857600
  kafkaMaxMessageBytes: 1000012
  kafkaHeapOpts: -Xmx500m -Xms500m
  minMem: 600Mi
  minCpu: 100m
  maxMem: 6Gi
  maxCpu: 1500m
- name: mon-metrics-agents
  alias: metrics-agents
  image: metrics-agents
  replicas: 1
  env: agentscheduler
  minMem: 300Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: mon-node-daemon
  alias: node-daemon
  image: node-daemon
  env: node-daemon
  minMem: 300Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: db-redis
  alias: redis
  image: redis
  minMem: 300Mi
  minCpu: 50m
  maxMem: 7Gi
  maxCpu: 1000m
  maxMemory: 6840mb
- name: util-client
  alias: client-util
  image: util-client
  minMem: 300Mi
  maxMem: 3Gi
  minCpu: 20m
  maxCpu: 1500m
- name: util-kibana
  alias: kibana
  image: util-kibana
  kibanaElsUrl: els1
  minMem: 100Mi
  maxMem: 500Mi
  minCpu: 20m
  maxCpu: 300m
- name: db-zk1
  alias: zk1
  image: zk
  kfkId: kfk1
  zooServerID: 1
  zooServers: 0.0.0.0:2888:3888,zk2:2888:3888,zk3:2888:3888
  zooHeapSize: 1024
  minMem: 300Mi
  minCpu: 50m
  maxMem: 2Gi
  maxCpu: 300m
- name: db-zk2
  alias: zk2
  image: zk
  kfkId: kfk2
  zooServerID: 2
  zooServers: zk1:2888:3888,0.0.0.0:2888:3888,zk3:2888:3888
  zooHeapSize: 1024
  minMem: 300Mi
  minCpu: 50m
  maxMem: 2Gi
  maxCpu: 300m
- name: db-zk3
  alias: zk3
  image: zk
  kfkId: kfk3
  zooServerID: 3
  zooServers: zk1:2888:3888,zk2:2888:3888,0.0.0.0:2888:3888
  zooHeapSize: 1024
  minMem: 300Mi
  minCpu: 50m
  maxMem: 2Gi
  maxCpu: 300m