version: v1
services:
- name: register-api
  alias: register-api
  image: automation-technology
  replicas: 1
  env: register-api
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: mail-consumer
  alias: mail-consumer
  image: automation-technology
  replicas: 1
  env: mail-consumer
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: batch-scheduler
  alias: batch-scheduler
  image: automation-technology
  replicas: 1
  env: batch-scheduler
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: batch-ptask-api
  alias: batch-ptask-api
  image: automation-technology
  replicas: 1
  env: batch-ptask-api
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: batch-ptask-worker
  alias: batch-ptask-worker
  image: automation-technology
  replicas: 1
  env: batch-ptask-worker
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
- name: external-api
  alias: external-api
  image: automation-technology
  replicas: 1
  env: external-api
  minMem: 30Mi
  maxMem: 8Gi
  minCpu: 20m
  maxCpu: 500m
