version: v1
services:
- name: kfk1
  image: kfk
  kfkId: kfk1
  kafkaBrokerID: 1
  kafkaPortNumber: 9092
  kafkaNumPartitions: 5
  kafkaZookeeperConnect: zk1:2181,zk2:2181,zk3:2181
  kafkaNumNetworkThreads: 3
  kafkaNumIOThreads: 4
  kafkaSocketSendBuffeBytes: 102400
  kafkaSocketReceiveBufferBytes: 102400
  kafkaSocketRequestMaxBytes: 104857600
  kafkaMaxMessageBytes: 1000012
  kafkaHeapOpts: -Xmx2560m -Xms2560m
  minMem: 300Mi
  minCpu: 100m
  maxMem: 6Gi
  maxCpu: 1500m
  clientId: c1
- name: kfk2
  image: kfk
  kfkId: kfk2
  kafkaBrokerID: 2
  kafkaPortNumber: 9092
  kafkaNumPartitions: 5
  kafkaZookeeperConnect: zk1:2181,zk2:2181,zk3:2181
  kafkaNumNetworkThreads: 3
  kafkaNumIOThreads: 4
  kafkaSocketSendBuffeBytes: 102400
  kafkaSocketReceiveBufferBytes: 102400
  kafkaSocketRequestMaxBytes: 104857600
  kafkaMaxMessageBytes: 1000012
  kafkaHeapOpts: -Xmx2560m -Xms2560m
  minMem: 300Mi
  minCpu: 100m
  maxMem: 6Gi
  maxCpu: 1500m
  clientId: c1
- name: kfk3
  image: kfk
  kfkId: kfk3
  kafkaBrokerID: 3
  kafkaPortNumber: 9092
  kafkaNumPartitions: 5
  kafkaZookeeperConnect: zk1:2181,zk2:2181,zk3:2181
  kafkaNumNetworkThreads: 3
  kafkaNumIOThreads: 4
  kafkaSocketSendBuffeBytes: 102400
  kafkaSocketReceiveBufferBytes: 102400
  kafkaSocketRequestMaxBytes: 104857600
  kafkaMaxMessageBytes: 1000012
  kafkaHeapOpts: -Xmx2560m -Xms2650m
  minMem: 300Mi
  minCpu: 100m
  maxMem: 6Gi
  maxCpu: 1500m
  clientId: c1