version: v1
services:
- name: util-client
  alias: client-util
  image: util-client
  minMem: 300Mi
  maxMem: 3Gi
  minCpu: 20m
  maxCpu: 1500m
  clientId: c1
- name: util-kibana
  alias: kibana
  image: util-kibana
  kibanaElsUrl: els1
  minMem: 100Mi
  maxMem: 500Mi
  minCpu: 20m
  maxCpu: 300m
  clientId: c1