SHELL := /bin/bash

default:
	echo 'Default command'
setup-tcir:
	devopsctl setup -d "tcir"
setup-db:
	devopsctl setup -d "db"
setup-mon:
	devopsctl setup -d "mon"
setup-util:
	devopsctl setup -d "util"